server:
    port: 8888


spring:
  application:
    name: config-server  # 服务名称
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/geemu/spring-cloud
          searchPaths: config-repository
          username: geemu
          password: 
